### ISSUE TITLE
Navigation gerado automaticamente

### ISSUE THREAD

**Issue by PedroAntunesCosta** [vtexdocs/helpcenter#109]
Como a estrutura de pastas do repo help-center-content reflete a arquitetura do conteúdo no portal. Podemos usar isso para gerar o navigation.json automaticamente.

Poderia ser uma Github action ativada em PRs do help-center-content:

1. Identificar arquivos e pastas modificados.
2. Validar se a estrutura de pastas nos 3 idiomas é a mesma (se não for, o TW precisa corrigir).
3. Editar o navigation.json com as mudanças encontradas. 

#### Prioridade baixa

A prioridade é baixa pois não bloqueia o lançamento. Podemos trabalhar nisso depois de lançar o portal.

**Comment by julia-rabello** [comment]
Precisamos considerar também o "status" do arquivo ou a propriedade "hidden", se não quisermos que algum artigo apareça na navegação.

**Comment by PedroAntunesCosta** [comment]
Decidimos que não usaremos navigation gerado automaticamente para manter a autonomia dos TWs em gerenciar a ordem dos elementos na sidebar.
