### ISSUE TITLE
Consertar sidebar do Dev Portal e Help Center

### ISSUE THREAD

**Issue by ThayllyR** [vtexdocs/helpcenter#39]
**Sobre o bug**
A âncora de ambos os portais sempre pula para o tópico seguinte. Ex: cliquei no primeiro tópico, a âncora direciona para o segundo. Cliquei no terceiro, para o quarto, e assim por diante. 

**To Reproduce**
Passo a passo para produzir e testar esse bug.

1. Acesse qualquer página interna de documentação. 
2. Encontre a âncora que está localizada no lado direito da página logo abaixo do autor.
3. Clique em qualquer um dos tópicos.
4. Veja o erro. 

**Expected behavior**
O objetivo dessa issue é consertar esse bug em ambas as bibliotecas (dev portal e help center)

![ancora](https://github.com/vtexdocs/helpcenter/assets/115578709/bce840e8-7a96-44d3-8210-af6ed120aad6)

Para ver o erro é só utilizar a âncora no link: 
https://developers.vtex.com/docs/guides/making-your-first-request#before-you-begin

**Comment by PedroAntunesCosta** [comment]
Testei agora e está funcionando corretamente. Deve ter sido ajustado nesse meio tempo.
