### ISSUE TITLE
Mudar a ordem de meses da sidebar de Comunicados

### ISSUE THREAD

**Issue by ThayllyR** [vtexdocs/helpcenter#43]
**Visão geral**
A ordem da sidebar de comunicados está diferente interna e externamente. Os anos estão em ordem decrescentes e os meses crescentes. O ideal é que os meses dentro de cada ano fiquem também em ordem decrescente (começando por dezembro e terminando em janeiro). Assim, ficará coerente. 

![comunicados](https://github.com/vtexdocs/helpcenter/assets/115578709/280d185f-d5a6-46af-8ba3-8ac63a3ab551)

**Comment by PedroAntunesCosta** [comment]
Com a [implementação de slugs localizadas](https://github.com/vtexdocs/helpcenter/pull/110), acabamos fazendo mudanças significativas na estrutura do navigation.json. Por isso fechei o PR acima.

Agora usamos [este script](https://github.com/vtexdocs/help-center-content/blob/main/generateNavigation.js) para gerar o json e acredito que o ideal seja atualizá-lo para retornar os **_meses e anos_** em ordem cronológica inversa.

Como a @julia-rabello acabou de mexer com isso e o @Icaro-Nunes está focado em outras issues, vou trocar aqui o assignee.
