### ISSUE TITLE
Consertar a tradução das tags de status para o idioma selecionado

### ISSUE THREAD

**Issue by ThayllyR** [vtexdocs/helpcenter#44]
**Descrição**
Os filtros de status não estão traduzidos nos cards. Ao traduzir o idioma do portal os filtros são traduzidos internamente no box, mas quando ele é fechado, essas tags ficam sempre em inglês (não importa o idioma). 

**Para reproduzir**
Passo a passo para averiguar o erro:

1. Vá para a página de Problemas conhecidos.
2. Se estiver em inglês, muda para o idioma português.
3. Selecionar um status e ver se ao aparecer na página está no idioma selecionado (português) ou está em inglês.
4. Veja o erro

**Expectativa dessa issue**
As tags devem ser sinalizadas no card no idioma selecionado e não somente em inglês. Se os status estão em português, as tags devem estar em português, espanhol ou inglês (de acordo com a seleção). 

https://github.com/vtexdocs/helpcenter/assets/115578709/ef3bd13c-e155-4188-8ced-eed419a8d411

**Comment by Icaro-Nunes** [comment]
@ThayllyR  Não consegui reproduzir o bug. Tentei mudar o idioma da página algumas vezes, e tentei mudar o idioma do meu sistema operacional algumas vezes, e o comportamento era o mesmo. Qual sistema operacional tás usando, e com qual idioma?


https://github.com/vtexdocs/helpcenter/assets/55800516/269f8b11-3416-4160-bbda-87e0d8e4f634

**Comment by ThayllyR** [comment]
Oi, Icaro... Então... Eu sou o MacOS mas a usuária entrevistada usa o windows. Seria também quando volta a homepage. Se esse erro estiver consertado, pode marcar como resolvido.
