### ISSUE TITLE
Adicionar botão de copy link

### ISSUE THREAD

**Issue by ThayllyR** [vtexdocs/helpcenter#54]
As páginas de artigo (documentação) terão um botão de copy link que funcionará como um encurtador de URL. O botão deve ficar sempre abaixo do título do lado oposto ao minuto de leitura, na página de problemas conhecidos deve ficar abaixo do botão de status e nas páginas onde há botão de share (comunicados) ele deve substituí-lo (o botão de share deve virar o botão de copy link). 

<img width="879" alt="Captura de Tela 2024-06-10 às 09 35 18" src="https://github.com/vtexdocs/helpcenter/assets/115578709/902d192c-a379-4104-9f08-91f08b9ebe5e">

<img width="803" alt="Captura de Tela 2024-06-10 às 09 28 18" src="https://github.com/vtexdocs/helpcenter/assets/115578709/0dcda3b0-b0cd-4d10-835c-e2df41e482ae">
<img width="736" alt="Captura de Tela 2024-06-10 às 09 30 32" src="https://github.com/vtexdocs/helpcenter/assets/115578709/27d9dc1b-e769-4951-9529-1fdfa27efb00">

**Describe the solution you'd like**
Adição do botão de copy link. 
![copylink](https://github.com/vtexdocs/helpcenter/assets/115578709/39ac6ffa-3448-45a4-a9b3-f859aa207b80)
![copylink2](https://github.com/vtexdocs/helpcenter/assets/115578709/8abcb3fd-63d1-42cd-b366-c1849ff72d07)

**Onde o botão deve ser adicionado?**

Nas páginas de artigo (de todas as categorias: comece aqui, tutoriais e soluções, problemas conhecidos, diretrizes de suporte, Perguntas Frequentes, Troubleshooting e Comunicados).

**Comment by Icaro-Nunes** [comment]
Adicionei o botão em todas as páginas assinaladas, exceto pela de troubleshooting (que não existe na main ainda) e a de Comunicados, porque já tem uma opção de copiar link.

![Captura de tela de 2024-06-19 18-38-07](https://github.com/vtexdocs/helpcenter/assets/55800516/3f7597f6-3e47-47d3-be40-03067eeee963)

Deixo essa página assim mesmo?
